### ISSUE TITLE
[Feature]: Add typescript

### ISSUE THREAD

**Issue by seriouslysean** [seriouslysean/monster-hunter-now-events#16]
### Feature Description

:)

**Comment by chris--jones** [comment]
I'm game to try and handle this one 😄

**Comment by seriouslysean** [comment]
That would be awesome! I've been looking for an excuse to get more practical experience and this is just a fun side project. If you want to take a crack as adding the initial config and maybe converting a file or two I think that would be a great start.

**Comment by chris--jones** [comment]
I don't get to code as much as I used to, so I use hacktoberfest as an excuse to get more practical experience myself! otherwise I'm worried I'll get rusty 😉

**Comment by seriouslysean** [comment]
Haha, tell me about it. I use it to keep up with new stuff. I do a lot of coding on the daily but not much time to continue learning TS-- the codebase I'm working on only uses it on the parts of the app I'm not working on at the moment.

If you need any help or want to talk through anything, let me know! Otherwise have at it and I'll PR it once you've taken a crack at it.

Thanks the for the assistance!

**Comment by seriouslysean** [comment]
@chris--jones good call, removed the caching for `npm ci` for now and it looks like it passes again.
