### ISSUE TITLE
[Feature]: Update GPT API calls to take advantage of JSON file support

### ISSUE THREAD

**Issue by seriouslysean** [seriouslysean/monster-hunter-now-events#25]
### Feature Description

https://github.com/seriouslysean/monster-hunter-now-events/issues/22#issuecomment-1758135005

@mdrokz brought up a great idea for the GPT API calls. Apparently JSON output is now officially supported. Currently I'm not taking advantage of that in the chat api script.

https://blog.simonfarshid.com/native-json-output-from-gpt-4

Instead of the current approach of making the prompt incredibly precise, it might be better to reduce the complexity of the prompt overall with regard to the JSON output rules, and instead rely on this official support.

**Comment by Vyvy-vi** [comment]
I'd like to work on this issue

**Comment by seriouslysean** [comment]
You got it, thanks for offering!

**Comment by seriouslysean** [comment]
@Vyvy-vi are you still interested in this issue?
