### ISSUE TITLE
[Feature]: Improve the documentation spelling and grammar

### ISSUE THREAD

**Issue by Akshith-S** [seriouslysean/monster-hunter-now-events#28]
### Feature Description

Hi,
I was looking through your project when I found out some errors in Readme file. I would like to improve the overall documentation of your project! Please assign me under Hacktoberfest label.
Thanks!

**Comment by ISaumya1011** [comment]
Hi @seriouslysean , I want to contribute to this issue under hacktoberfest 2023. Please share the documentation which needs to be improved for overall organisation and documentation layout. Thank you!

**Comment by seriouslysean** [comment]
@ISaumya1011 hey thanks for the offer! @Akshith-S is already picking this up at the moment though. If you don't see a specific ticket please feel free to offer any suggestions on improvements to the documentation.

Ticket #30 revolves more around overall structure and adding a TOC for the individual sections if that's more your speed.

**Comment by nikhilnrr** [comment]
Hi @seriouslysean , I don't see anyone assigned yet. If this is still available to work on, it'd be helpful for my resume :)

**Comment by ISaumya1011** [comment]
Thank you for assigning this task to me. Happy to work upon it!

**Comment by ISaumya1011** [comment]
@seriouslysean I have made the changes. But I think there was some issue in proposing the changes. A new issue number is created. It is showing one pending approval request and the previous merge request was blocked. Kindly check at your end and see if the earlier proposed changes for it can be merged. Thank you!

**Comment by ISaumya1011** [comment]
Also, please let me know if I need to propose the changes in some other way.

**Comment by seriouslysean** [comment]
Invalid for the time being, closing and will potentially reopen later.
