### ISSUE TITLE
[Feature]: Improve documentation organization & layout

### ISSUE THREAD

**Issue by seriouslysean** [seriouslysean/monster-hunter-now-events#30]
### Feature Description

- Better organization
- Add TOCS
- Logical file splitting
- Documentation for each tool + purpose

**Comment by ISaumya1011** [comment]
Hi @seriouslysean  , I want to contribute to this issue under hacktoberfest 2023. Please share the documentation which needs to be improved.

**Comment by shivamkasaudhan** [comment]
Hello @seriouslysean,
I would like to contribute to this issue. This would be my very first contribution to open-source. Could you please assign it to me?
Thank you!

**Comment by seriouslysean** [comment]
Assigning to @ISaumya1011 as they responded first, thanks for the interest!

**Comment by ISaumya1011** [comment]
Thank you so much for giving me this opportunity, I will try my best to do the needful!

**Comment by seriouslysean** [comment]
This issue is blocked until #28 is done to prevent merge conflicts.

**Comment by ISaumya1011** [comment]
Okay sure, I had already proposed the changes. Kindly let me know when #28 is done. Will proceed with the rest of the task.

**Comment by seriouslysean** [comment]
Resolved by #50
