### ISSUE TITLE
[Feature]: Add support to switch between GPT models

### ISSUE THREAD

**Issue by seriouslysean** [seriouslysean/monster-hunter-now-events#41]
### Feature Description

For instance, 3.5 turbo and 4. This should probably be handled via an env of some sort.

It’s possible there may need to be different prompts between models depending on specificity, too. The prompts I’ve made so far work best with 4.

**Comment by mdrokz** [comment]
> ### Feature Description
> 
> For instance, 3.5 turbo and 4. This should probably be handled via an env of some sort.
> 
> It’s possible there may need to be different prompts between models depending on specificity, too. The prompts I’ve made so far work best with 4.

Hi can you assign me this issue please?
