### ISSUE TITLE
[Feature]: Do not save events.json on error

### ISSUE THREAD

**Issue by seriouslysean** [seriouslysean/monster-hunter-now-events#46]
### Feature Description

Saving events.json with an empty array of events stops it from redownloading or trying again in the future.

**Comment by ofMoons** [comment]
@seriouslysean - I've been poking around at this, it looks as simple as a conditional bailing early if the .events array is empty.  Is the check you are thinking of after the ChatGPT request responds?  Do you have recommended steps for verifying this feature is working as desired?

**Comment by seriouslysean** [comment]
You should be able to just run `npm start` twice, once to pull the data, then again to make sure it noops properly.

There’s already a check for the hash when merging the fixtures so after gpt makes sense. I’m imagining a dupe event which then sometimes do, where we get a new entry in the fixture but gpt sends back the same response.

It’s really tricky because GPT may never convince events or dedupe them in the same way.

**Comment by Dxuian** [comment]
still open?

**Comment by seriouslysean** [comment]
Nah, this whole project is archived— thanks for the interest though! I’ll make sure to double check that I removed it from hacktoberfest.
