### ISSUE TITLE
[Feature]: Add logger utility to consolidate and remove console usages

### ISSUE THREAD

**Issue by seriouslysean** [seriouslysean/monster-hunter-now-events#7]
I'm imagining either a new `utils/logger-utils.js` file with some functions for logging `info`/`warnings`/`errors`, could probably even use chalk to make it look nicer in the console.

https://www.npmjs.com/package/chalk

Eventually, I'd like to move to passing errors to rollbar or something like it so a basic implementation would be a good start.

**Comment by christianfds** [comment]
I can do this, is there any preference on which lib to be used?

**Comment by seriouslysean** [comment]
@christianfds I'm not entirely sure. It doesn't need to be anything special. I was imagining either a new logger utils file with some functions for logging info/warnings/errors, could probably even use chalk to make it look nicer in the console.

Eventually, I'd like to move to passing errors to rollbar or something like it so a basic implementation would be a good start.

**Comment by christianfds** [comment]
Awesome! I will write a facade or leverage a package (like slf4j on java) so any changes are easier in case you need to

**Comment by seriouslysean** [comment]
@christianfds you can use the basis I added in here when adding rollbar. This might make some of what you're doing easier.

https://github.com/seriouslysean/monster-hunter-now-events/pull/27
